### ISSUE TITLE
THUMBNAIL_REMOVE_URL_ARGS is not in documentation

### ISSUE THREAD

**Issue by legendemil** [jazzband/sorl-thumbnail#645] opened 2020-08-28 11:36 UTC
Hi,
the THUMBNAIL_REMOVE_URL_ARGS option is not documented, I think it would be great to add this to documentation, because default to this option is True and it removes query args from the url and thumbnail generation from Amazon presigned urls doesn't work.

https://stackoverflow.com/questions/63631469/django-sorl-thumbnail-doesnt-generate-thumbnail-from-amazon-presigned-url

**Comment by claudep** [comment] 2022-02-05 22:04
Duplicate of #649

**Closed by claudep** 2022-02-05 22:04 UTC
