### ISSUE TITLE
Django storage class instantiated every time

### ISSUE THREAD

**Issue by cristianocca** [jazzband/sorl-thumbnail#508] opened 2017-07-28 15:03 UTC
https://github.com/jazzband/sorl-thumbnail/blob/master/sorl/thumbnail/default.py#L24

Is it needed that the storage class is created every time it's needed? What happens if the storage class has a slow constructor? This happens with a custom AWS S3 storage class, that will check for the bucket on class construction only.

**Comment by cristianocca** [comment] 2017-07-28 15:15
Sorry, it seems the culprit is here, when rendering images:

https://github.com/jazzband/sorl-thumbnail/blob/master/sorl/thumbnail/images.py#L40

**Comment by bartels** [comment] 2019-01-21 02:53
This appears to be the same bug as #301 

It's particularly bad with the latest boto3 storage from django-storages, as it adds a large delay for each thumbnail generated.

It looks to be due to the behavior of instantiating a new storage instance for each thumbnail when deserializing from the cache. What would fix it is having some module level variable to cache the storage instances. That way only a single storage instance would be initialized for each storage type.

**Comment by claudep** [comment] 2023-08-15 06:42
Duplicate of #301

**Closed by claudep** 2023-08-15 06:42 UTC
