### ISSUE TITLE
Why version 12.4 is not releases in pypi

### ISSUE THREAD

**Issue by sacrac** [jazzband/sorl-thumbnail#519] opened 2017-10-13 04:11 UTC
Hi, when install pip install sorl-thumbnail
the version install is 12.3 why?
i see releases in github is version 12.4

how to install this final releases 12.4??

**Comment by sacrac** [comment] 2017-10-13 04:14
ok i install this way
pip install https://github.com/jazzband/sorl-thumbnail/archive/v12.4.zip
but why not deploy in pypi??

**Comment by Flimm** [comment] 2017-10-13 08:11
This is a duplicate of https://github.com/jazzband/sorl-thumbnail/issues/507

**Closed by Flimm** 2017-10-13 08:11 UTC
