### ISSUE TITLE
Cached thumb penalty with S3 backend

### ISSUE THREAD

**Issue by lorinkoz** [jazzband/sorl-thumbnail#662] opened 2020-12-30 14:53 UTC
👋🏼 Good work with this package!

---

Because of this code:

https://github.com/jazzband/sorl-thumbnail/blob/29644a4abb727ed57877688027cad156b63dfc32/sorl/thumbnail/images.py#L37-L41

If multiple thumbs with S3 backend are fetched from cache, the fact that they will all use a different storage will incur in a time penalty when generating presigned URLs for each one of those, as the object `backend.connection` will not be initialized every time.

**Comment by dirigeant** [comment] 2021-01-15 16:38
same issue with #301 and #508

**Comment by krukas** [comment] 2023-01-24 12:55
I created a PR to fix this https://github.com/jazzband/sorl-thumbnail/pull/719

In the mean time a fix for others with this problem. I have used the Redis KVStore, this should work for all stores.

```python
from sorl.thumbnail.kvstores.redis_kvstore import KVStore
from sorl.thumbnail.kvstores.base import add_prefix
from sorl.thumbnail.helpers import get_module_class, deserialize
from sorl.thumbnail.images import ImageFile

STORAGES_CACHE = {}


def get_or_create_storage(storage):
    if storage not in STORAGES_CACHE:
        STORAGES_CACHE[storage] = get_module_class(storage)()
    return STORAGES_CACHE[storage]


class SorlThumbnailRedisKVSTore(KVStore):
    def _get(self, key, identity='image'):
        """
        Deserializing, prefix wrapper for _get_raw
        """
        value = self._get_raw(add_prefix(key, identity))

        if not value:
            return None

        if identity == 'image':
            return self._deserialize_image_file(value)

        return deserialize(value)

    def _deserialize_image_file(self, s):
        data = deserialize(s)

        image_file = ImageFile(data['name'], get_or_create_storage(data['storage']))
        image_file.set_size(data['size'])
        return image_file
```

**settings**
```python
THUMBNAIL_KVSTORE = "<your module path>.SorlThumbnailRedisKVSTore"
```

**Comment by claudep** [comment] 2023-08-15 06:43
Duplicate of #301

**Closed by claudep** 2023-08-15 06:43 UTC
