### ISSUE TITLE
Files are not preserved as gifs, even if THUMBNAIL_PRESERVE_FORMAT is set to True

### ISSUE THREAD

**Issue by PSzczepanski1996** [jazzband/sorl-thumbnail#633] opened 2020-04-28 08:41 UTC
```
THUMBNAIL_ENGINE = 'sorl.thumbnail.engines.pil_engine.Engine'
THUMBNAIL_PRESERVE_FORMAT = True
THUMBNAIL_FORMAT = 'PNG'
```

```
sorl-thumbnail==12.6.3
Pillow==7.1.2
```

**Comment by claudep** [comment] 2024-10-26 07:19
Duplicate of #687

**Closed by claudep** 2024-10-26 07:19 UTC
