### ISSUE TITLE
Broken link in the docs

### ISSUE THREAD

**Issue by koutoftimer** [jazzband/sorl-thumbnail#747] opened 2023-11-14 09:36 UTC
https://sorl-thumbnail.readthedocs.io/en/latest/operation.html has broken link "[Schematic view of how things are done](https://docs.google.com/drawings/edit?id=1wlE4LkQpzXd2a2Nxfjt6_j5NG7889dzMyf0V-xPAJSE&hl=en)"

**Comment by claudep** [comment] 2024-09-28 14:42
Duplicate of #714

**Closed by claudep** 2024-09-28 14:42 UTC
